### ISSUE TITLE
Technical roadmap for specializer

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#127]
- [x] Merge latest changes into branch instrumented_apt.
 - [x] Merge instrumented_apt into master in some form #41.
 - [x] Redo measurement of literal value popularity #124.
 - [x] Exploit word encoding in specializer #125.
 - [x] Specialize for constants on top of the stack #126.

**Comment by apt1002** [comment]
Longer term:

 - Understand `BRANCHZ` better. At the moment there is an "if" in the `BRANCHZ` action which modifies `PC` and `I`, but has no effect on control flow, followed by an "if" in the interpreter which checks the value of `I`. There should only be one "if", and in the non-taken case the interpreter should be allowed to guess the future beyond a `BRANCHZ` instruction. This looks moderately hard.

 - Specialize the second and subsequent iterations of a loop. If the `PC` values repeat (not just the `I` values) we can avoid instruction fetch altogether, assuming the code doesn't modify itself.

**Comment by apt1002** [comment]
All the checkboxes are now ticked.

I'm not sure what to do with the "longer term" work items. Our current test cases do not require them, as the specializer doesn't really get its teeth into anything but the pForth function prologue and epilogue. I will close this issue for now.
