### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#309]
# 0.1 Release

- [ ] Get pForth working on `instruction-set-changes` branch.
- [ ] Review core code (everything except `specializer` and `features` subdirectories of `src`).
- [ ] Close specializer issues or move them to Mijit (#316, #358, #360)

# 0.9 Release

- [ ] Plugin mechanism (branch `instruction-set-extra-overhaul`)
- [ ] Split out FFI (#289).
- [ ] 8-byte pForth.

# 1.0 Release

- [ ] Spec as data (#52)
- [ ] Separate code & data: code & data labels (see Mite), extra instruction(s) to load code at run-time, for run-time code generation.
- [ ] Mijit JIT

# Post-1.0

- [ ] A C compiler targeting Mit
- [ ] A sensible FFI story
