### ISSUE TITLE
Roadmap for 0.1

### ISSUE THREAD

**Issue by mk270** [rrthomas/smite#44]
Version 0.1

- [x] Issues tagged "0.1".
- [x] Check FIXMEs.
- [x] Have a somewhat tidied-up pForth as a demonstration
- [x] Have some version of optimization working #41
- [x] Conform as much as possible to the current version of Mite (the conformation might of course go both ways—broadly speaking the only difference remaining should be stack vs registers) #106
- [x] At release, mention on @rrthomas's web site.
- [x] Remove memory mapping from Beetle for fairer speed comparison.

(pForth and optimization need not themselves be release quality!)

**Comment by apt1002** [comment]
See also #127.

**Comment by rrthomas** [comment]
We're not actually going to make a 0.1 release, so closing this issue.
